In [1]:
#import stuff

import numpy as np
from CreateDataFunctions import *
import sklearn.decomposition as dec
import matplotlib.pyplot as plt

In [4]:
#initialize data

nrObservations = 1000
nrFeatures = 200
seed = 30

normalData = normal_data(nrObservations, nrFeatures, seed)
uniformData = uniform_data(nrObservations, nrFeatures, seed)

[[0.64414354 0.38074849 0.66304791 ... 0.03627233 0.86190789 0.04770621]
 [0.42890595 0.99741096 0.69250201 ... 0.49702537 0.92923405 0.02921423]
 [0.04920976 0.34234193 0.99185205 ... 0.19796587 0.98691821 0.88486526]
 ...
 [0.84050178 0.98354691 0.19384042 ... 0.35917472 0.5579789  0.91567274]
 [0.84145683 0.19616706 0.0332312  ... 0.34035263 0.21879263 0.80537939]
 [0.87062944 0.07933762 0.57698296 ... 0.19720183 0.94870927 0.60956792]]
