In [13]:
#import stuff

import numpy as np
from CreateDataFunctions import *
import sklearn.decomposition as dec
import matplotlib.pyplot as plt

In [14]:
#import data

nrObservations = 1000
nrFeatures = 200
seed = 30
nrDimToKeep = 30

normalData = normal_data(nrObservations, nrFeatures, seed)
uniformData = uniform_data(nrObservations, nrFeatures, seed)
normalDataCov = normal_data_with_cov(nrObservations, nrFeatures, seed)

datasets_original = [normalData, uniformData, normalDataCov]

In [ ]:
# plot data

#normal
plt.scatter(normalData[:,0],normalData[:,1],s=1)
plt.title('Normal data')
plt.axis('equal')
plt.show()

#uniform
plt.scatter(uniformData[:,0],uniformData[:,1],s=1)
plt.title('Uniform data')
plt.axis('equal')
plt.show()

#normal with cov
plt.scatter(normalDataCov[:,0],normalDataCov[:,1],s=1)
plt.title('Normal data with covariance')
plt.axis('equal')
plt.show()

In [15]:
# create pca and isomap data sets

from sklearn.decomposition import PCA
from sklearn.manifold import Isomap

nrFeaturesKeep = 10
datasets_PCA = []
datasets_ISO = []
for i,X in enumerate(datasets_original):
    pca = PCA(nrFeaturesKeep)
    pca = pca.fit(X)

    isomap = Isomap(n_components=nrFeaturesKeep)
    isomap = isomap.fit(X)

    datasets_PCA.append(pca.transform(X))
    datasets_ISO.append(isomap.transform(X))

In [24]:
import numpy as np
from sklearn.cluster import KMeans

#def k maeans
def Kmeans(X,k=K):
    # Clusters data into k clusters, where k can be a vector of different integers, 
    # in which case clustering is made for each k.
    if isinstance(k, int):
        kmeans = KMeans(n_clusters=k).fit(X)
        return kmeans.labels_

    labels = np.zeros([X.shape[0],len(k)])

    for i in range(len(k)):
        kmeans = KMeans(n_clusters=k[i]).fit(X)
        labels[:,i] = kmeans.labels_

    return labels


#run k means on data set
K = 5
labels_PCA = []
labels_ISO = []
labels_original = []
for X in datasets_original:
    labels_original.append(Kmeans(X, k=K))
for X in datasets_PCA:
    labels_PCA.append(Kmeans(X, k=K))
for X in datasets_ISO:
    labels_ISO.append(Kmeans(X, k=K))

In [28]:
import numpy as np
from sklearn.cluster import KMeans

#def k maeans
def Kmeans(X,k=K):
    # Clusters data into k clusters, where k can be a vector of different integers, 
    # in which case clustering is made for each k.
    if isinstance(k, int):
        kmeans = KMeans(n_clusters=k).fit(X)
        return kmeans.labels_

    labels = np.zeros([X.shape[0],len(k)])

    for i in range(len(k)):
        kmeans = KMeans(n_clusters=k[i]).fit(X)
        labels[:,i] = kmeans.labels_

    return labels


#run k means on data set
labels_PCA_varyingK = []
labels_ISO_varyingK = []
labels_original_varyingK = []
k_vec = [1,2,3,4,5]

for K in k_vec: 
    labels_PCA = []
    labels_ISO = []
    labels_original = []
    for X in datasets_original:
        labels_original.append(Kmeans(X, k=K))
    for X in datasets_PCA:
        labels_PCA.append(Kmeans(X, k=K))
    for X in datasets_ISO:
        labels_ISO.append(Kmeans(X, k=K))
    labels_PCA_varyingK.append(labels_PCA)
    labels_ISO_varyingK.append(labels_ISO)
    labels_original_varyingK.append(labels_original)
    

In [27]:
#plotting original data (no pca or iso)

K = 2
dataset_to_plot = 1 #0-Normal, 1-Uniform, 2- Normal w/ cov

labels_plt = datasets_original[dataset_to_plot]
labels_plt = labels_original_varyingK[K-1][dataset_to_plot]
    
LABEL_COLOR_MAP = {0 : 'r',
                   1 : 'b',
                   2 : 'g',
                   3 : 'm',
                   4 : 'y',
                   5 : 'c',
                   6 : 'orange',
                   7 : 'cyan',
                   8 : 'pink',
                   9 : 'navy'
                   }

label_colors_PCA = [LABEL_COLOR_MAP[l] for l in cl_PCA]
label_colors_ISO = [LABEL_COLOR_MAP[l] for l in cl_ISO]


f, (ax1, ax2) = plt.subplots(1, 2, sharey=True)

ax1.plot(Y_PCA[:,0],Y_PCA[:,1],'.',c=label_color_PCA)

ax2.plot(Y_ISO[:,0],Y_ISO[:,1],'.',c=label_color_ISO)

[array([1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1,
        1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1,
        0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0,
        0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1,
        0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1,
        1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
        0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
        1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0,
        0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1,
        1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1,
        0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0,
        0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1,
        1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
        1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 

In [33]:
K = 2
dataset_to_plot = 1 #0-Normal, 1-Uniform, 2- Normal w/ cov

data_plt = datasets_original[dataset_to_plot]
labels_plt = labels_original_varyingK[K-1][dataset_to_plot]
print(data_plt)
print(labels_plt)

[[0.64414354 0.38074849 0.66304791 ... 0.03627233 0.86190789 0.04770621]
 [0.42890595 0.99741096 0.69250201 ... 0.49702537 0.92923405 0.02921423]
 [0.04920976 0.34234193 0.99185205 ... 0.19796587 0.98691821 0.88486526]
 ...
 [0.84050178 0.98354691 0.19384042 ... 0.35917472 0.5579789  0.91567274]
 [0.84145683 0.19616706 0.0332312  ... 0.34035263 0.21879263 0.80537939]
 [0.87062944 0.07933762 0.57698296 ... 0.19720183 0.94870927 0.60956792]]
[1 1 1 0 1 1 1 0 1 1 0 0 0 1 0 0 1 0 1 1 0 0 1 1 1 0 1 1 0 0 0 1 0 0 1 1 1
 0 0 0 1 1 0 0 1 0 1 1 0 0 1 0 1 1 1 1 1 0 1 0 0 1 1 0 1 0 1 0 0 0 1 1 0 0
 0 0 0 0 1 1 1 1 1 1 0 0 1 0 0 1 1 1 1 1 0 0 1 1 0 0 0 1 1 0 1 1 0 1 0 1 1
 1 1 0 0 0 0 1 1 1 1 0 1 0 1 0 0 1 0 1 0 1 0 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0
 1 0 1 1 0 0 0 1 0 1 0 0 0 1 0 0 0 1 1 1 1 1 1 0 0 1 0 1 1 1 0 1 0 0 1 1 0
 0 1 1 0 0 0 1 1 0 1 0 0 1 0 1 1 1 1 0 0 1 1 1 1 0 1 1 1 1 1 1 1 1 0 1 0 1
 1 1 0 1 1 1 0 0 0 0 0 1 1 0 1 1 0 0 1 1 1 1 1 0 1 0 0 0 1 0 0 1 0 1 0 1 0
 0 1 1 0 0 0 0 0 0 1 0 1 1 1 0 